webauth.settings:
  type: config_object
  label: 'Webauthn settings'
  mapping:
    relying_party_name:
      type: string
      label: 'Relying party name'
    relying_party_id:
      type: string
      label: 'Relying party name'
    relying_party_icon:
      type: string
      label: 'Icon'
